#	Parameters for Gaussian components	
#
#	Each row represents a Gaussian component --- add as many as you like --- EXCEPT:
#   
#   THE THIRD LAST ROW REPRESENTS THE GAUSSIAN STANDARD DEVIATION (ONLY FOR THE psn MODE)
#   IF YOU WANT TO PLOT SOMETHING LIKE L/I VS. PA VARIANCE:
#      THE SECOND LAST ROW REPRESENTS A VARIANCE RANGE FROM THIRD LAST ROW FOR PLOTTING 
#      THE LAST ROW IS THE STEP SIZE BETWEEN THIRD AND SECOND LAST ROWS
#           - only one value can be varied --- make sure only one value in the final row is != 0
#           - last 3 columns cannot be varied
#
#	Columns:
#	t0  		    - Time offset of the Gaussian pulse in milliseconds
#	width		    - Width of the Gaussian pulse in milliseconds
#	A		- Peak amplitude of the Gaussian pulse (Jy)
#	spec_idx		- Spectral index of the Gaussian pulse
#   tau             - Scattering timescale in milliseconds
#	DM			    - Dispersion measure in pc/cm^3
#	RM			    - Rotation measure in rad/m^2
#	PA		        - Polarisation angle in degrees
#	(L/I)		    - Linear polarisation fraction
#	(V/I)		    - Circular polarisation fraction
#	dPA             - Change in polarisation angle with time in deg/ms
#   band_centre     - Central frequency of the Gaussian in MHz
#   band_width      - Frequency bandwidth of the Gaussian in MHz
#   N          - Number of micro-gausssians used to generate the pulse in psn mode
#   mg_width_low    - Lower width range of the micro-gaussians as a percentage of width
#   mg_width_high   - Higher width range of the micro-gaussians as a percentage of width

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#  t0    width  A  spec_idx   tau    DM    RM     PA    lfrac   vfrac   dPA   band_centre  band_width  N  mg_width_low  mg_width_high                   #
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------#
  0.0   0.1     5.0       0.0        1.56   0.0   0.0   -10     0.9    -0.1    0.0      0.0          0.0       175       5            20                             # gaussian
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------#
  0.0   0.0     0.0       0.0        0.0   0.0   0.0    10     0.0     0.0    0.0      0.0          0.0         0       0             0                             # psn std dev / start
  0.0   0.0     0.0       0.0        0.0   0.0   0.0     0     0.0     0.0    0.0      0.0          0.0         0       0             0                             #             / stop
  0.0   0.0     0.0       0.0        0.0   0.0   0.0     0     0.0     0.0    0.0      0.0          0.0         0       0             0                             #             / step
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------#