#	Parameters for Gaussian components	
#
#	Each row represents a Gaussian component --- add as many as you like --- EXCEPT:
#   
#   For single FRB plots (i.e., lvpa):
#     use rows 1 + (-4); ignore (-3)â€“(-5) (--sweep-mode none (default))
#   THE FOURTH LAST ROW REPRESENTS THE GAUSSIAN STANDARD DEVIATION 
#
#   IF YOU WANT TO PLOT SOMETHING LIKE L/I VS. PA VARIANCE:
#     THERE ARE TWO CASES: 
#       CASE 1 (MEAN SWEEP): ignore mean and std dev values and use start, stop, step to sweep parameter as constants 
#                             (i.e., update the mean with the sweep value and keep the std dev 0 the whole time)
#                             (--sweep-mode mean)
#
#       CASE 2 (VARIANCE SWEEP): keep mean and update the standard deviation with start, stop, step
#                                (--sweep-mode variance)
#
#         THE THIRD LAST ROW REPRESENTS THE STARTING POINT OF THE PARAMETER SWEEP
#         THE SECOND LAST ROW REPRESENTS THE END POINT FROM THIRD LAST ROW FOR PLOTTING 
#         THE LAST ROW IS THE STEP SIZE BETWEEN THIRD AND SECOND LAST ROWS
#              - only one value can be varied --- make sure only one value in the final row is != 0
#              - last 3 columns cannot be varied
#
#
#	Columns:
#	t0  		        - Arrival time of the Gaussian envelope in milliseconds
#	width		        - FWHM of the Gaussian envelope in milliseconds ( used as arrival_time_microshot_i ~ N(t0,width/(2*sqrt(2log2))) )
#	A	    	        - Amplitude of the Gaussian pulse (Jy)      |
# tau             - Scattering timescale in milliseconds      |
#	DM			        - Dispersion measure in pc/cm^3             | at reference frequency supplied in simparams.toml
#	RM			        - Rotation measure in rad/m^2               |
#	PA		          - Polarisation angle in degrees
#	(L/I)		        - Linear polarisation fraction
#	(V/I)		        - Circular polarisation fraction
#	dPA             - Change in polarisation angle with time in deg/ms
# band_centre     - Central frequency of the Gaussian in MHz
# band_width      - Frequency bandwidth of the Gaussian in MHz
# N          - Number of micro-gausssians used to generate the pulse
# mg_width_low    - Lower FWHM range of the micro-gaussians as a percentage of width  |
# mg_width_high   - Higher FWHM range of the micro-gaussians as a percentage of width | Uniform distribution, w_i ~ width * U(mg_width_low/100, mg_width_high/100)
#
#-------------------------------------------------------------------------------------------------------------------------------------------------#
#  t0   width   A         spec_idx   tau    DM    RM     PA    lfrac   vfrac   dPA   band_centre  band_width    N     mg_width_low  mg_width_high #
#-------------------------------------------------------------------------------------------------------------------------------------------------#
  -2.0  0.5     0.2       0.0        0  0.0   0.0    20     0.95   -0.05   0.0      0.0          0.0       100       5            20           # gaussian / gaussian mean
#-------------------------------------------------------------------------------------------------------------------------------------------------#
  0.0   0.0     0.0       0.0        0.0   0.0   0.0    30     0.0     0.0    0.0      0.0          0.0         0       0             0           #          / gaussian std dev (psn mode)
  0.0   0.0     0.0       0.0        0.0   0.0   0.0     0     0.0     0.0    0.0      0.0          0.0         0       0             0           # start
  0.0   0.0     0.0       0.0        0.5   0.0   0.0     0     0.0     0.0    0.0      0.0          0.0         0       0             0           # stop
  0.0   0.0     0.0       0.0        0.1   0.0   0.0     0     0.0     0.0    0.0      0.0          0.0         0       0             0           # step
#-------------------------------------------------------------------------------------------------------------------------------------------------#